[package]
name = "netkeeper"
version = "3.0.0"
description = "Keep your MTN networks alive"
authors = ["NetKeeper"]
edition = "2021"

[build-dependencies]
tauri-build = { version = "1.4", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tauri = { version = "1.5", features = [ "api-all", "system-tray"] }

[target.'cfg(target_os = "macos")'.dependencies]
objc = "0.2"

[features]
default = [ "custom-protocol" ]
custom-protocol = [ "tauri/custom-protocol" ]
api-all = [ "tauri/api-all" ]
system-tray = [ "tauri/system-tray" ]
